default_config:
logger:
  default: error
  logs:
    custom_components.srp_energy: debug



sensor:
  - platform: srp_energy
    username: YOUR_USERNAME
    password: YOUR_PASSWORD
    id: YOUR_ACCOUNT_ID